-- MySQL Script generated by MySQL Workbench
-- Thu Jun 12 22:16:52 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `theslap` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `theslap` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `theslap` ;

-- -----------------------------------------------------
-- Table `comentarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `comentarios` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `comentarios` (
  `id_comentarios` INT NOT NULL AUTO_INCREMENT,
  `comentario_texo` TINYTEXT NOT NULL,
  `fk_usuarios` INT NOT NULL,
  `fk_posteos` INT NOT NULL,
  PRIMARY KEY (`id_comentarios`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `estado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `estado` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `estado` (
  `id_estado` INT NOT NULL AUTO_INCREMENT,
  `tipo_estado` VARCHAR(45) NULL,
  PRIMARY KEY (`id_estado`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `eventos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eventos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `eventos` (
  `id_eventos` INT NOT NULL AUTO_INCREMENT,
  `info_evento` VARCHAR(45) NOT NULL,
  `fecha` DATE NOT NULL,
  `foto_evento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_eventos`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `posteos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `posteos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `posteos` (
  `id_posteos` INT NOT NULL AUTO_INCREMENT,
  `post_texto` TINYTEXT NOT NULL,
  `multimedia` VARCHAR(55) NULL,
  `fecha` DATE NOT NULL,
  `like` INT NULL,
  `fk_usuarios` INT NOT NULL,
  PRIMARY KEY (`id_posteos`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `reseñas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reseñas` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `reseñas` (
  `id_reseñas` INT NOT NULL AUTO_INCREMENT,
  `reseña_texto` VARCHAR(45) NOT NULL,
  `fecha` DATE NOT NULL,
  `fk_eventos` INT NOT NULL,
  `fk_usuarios` INT NULL,
  PRIMARY KEY (`id_reseñas`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `roles` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `roles` (
  `id_roles` INT NOT NULL AUTO_INCREMENT,
  `tipo_rol` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_roles`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `tipo_rol_UNIQUE` ON `roles` (`tipo_rol` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `usuarios` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `usuarios` (
  `id_usuarios` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `mail` VARCHAR(55) NOT NULL,
  `contrasenia` VARCHAR(45) NOT NULL,
  `avatar` VARCHAR(55) NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `fecha_creacion` DATE NOT NULL,
  `fk_role` INT NOT NULL,
  `fk_estado` INT NOT NULL,
  PRIMARY KEY (`id_usuarios`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `mail_UNIQUE` ON `usuarios` (`mail` ASC);

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
